const data = {
    products: [
      {
        _id: '1',
        name: 'Smoking',
        category: 'Shirts',
        image: '/images/smoking.jpeg',
        price: 1200,
        brand: 'Aldo',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '2',
        name: 'Style 1',
        category: 'Shirts',
        image: '/images/chaleco 2.webp',
        price: 1000,
        brand: 'Aldo',
        rating: 4.0,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '3',
        name: 'Style 2',
        category: 'Shirts',
        image: '/images/chaleco 3.webp',
        price: 2200,
        brand: 'Lacoste',
        rating: 4.8,
        numReviews: 17,
        description: 'high quality product',
      },
      {
        _id: '4',
        name: 'Style 3',
        category: 'Pants',
        image: '/images/saco rosa.jpeg',
        price: 78,
        brand: 'Aldo',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {
        _id: '5',
        name: 'Style 4',
        category: 'Pants',
        image: '/images/chaleco 5.webp',
        price: 1560,
        brand: 'Puma',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
      {
        _id: '6',
        name: 'Style 5',
        category: 'Pants',
        image: '/images/chaleco 6.jpeg',
        price: 1390,
        brand: 'Adidas',
        rating: 4.5,
        numReviews: 15,
        description: 'high quality product',
      },
    ],
  };
  export default data;